import type { Metadata } from 'next'
import "@radix-ui/themes/styles.css"
import "./globals.css"
import { Theme } from '@radix-ui/themes'

export const metadata: Metadata = {
  title: 'DBA ESPN',
  description: 'Generated by me mf',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
            <Theme>
                {children}
            </Theme>
        </body>
    </html>
  )
}
